In [1]:
import tensorflow as tf


In [2]:
# Launch the graph in a session.
with tf.compat.v1.Session() as ses:

     # Build a graph.
     a = tf.constant(5.0)
     b = tf.constant(6.0)
     op = a * b

     # Evaluate 
     print(ses.run(op))

30.0


In [3]:
d = tf.constant([3,1,5,8,6]) #1xn

e = tf.constant([[2,5,4], [3,5,7]]) #nxn
e2 = tf.constant([[1,2], [3,1,], [6,8]])

#d é um tensor  1-dimensional (vetor)
#e é um tensor 2-dimensional (matriz)

import numpy as np
a1 = np.array(2)
b2 = np.array([3,1,5,8,6]) #1xn
c3 = np.array([[2,2,4], [3,5,7]]) #nxn


In [4]:
print(e) #2lines 3columns

tf.Tensor(
[[2 5 4]
 [3 5 7]], shape=(2, 3), dtype=int32)


In [5]:
e.shape

TensorShape([2, 3])

In [6]:




#MULTIPLICANDO MATRIZES

multmatrices = tf.matmul(e,e2)

In [7]:
print(multmatrices)

tf.Tensor(
[[41 41]
 [60 67]], shape=(2, 2), dtype=int32)


In [8]:




#TRANSPOR A MATRIZ
transposta = tf.transpose(e)

In [9]:
print(transposta)

tf.Tensor(
[[2 3]
 [5 5]
 [4 7]], shape=(3, 2), dtype=int32)


In [10]:




#CRIANDO UMA VARIÁVEL QUE POSSA SER ATUALIZADA
variavel = tf.Variable(2)
tf.print(variavel)


2


In [11]:
matriz = tf.random.normal([3,3], 8, 1, tf.float32)   # shape [3,3] média = 8  desvio padrão = 1) dtype= float32
variavel2 = tf.Variable(matriz)
print(variavel2)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[8.641018 , 8.7560215, 9.414833 ],
       [8.148362 , 8.830062 , 7.1232753],
       [8.053048 , 6.952537 , 8.853811 ]], dtype=float32)>


In [15]:
dados_x = np.random.randn(4,8)   # cria matriz de 4 linhas e 8 colunas com números aleatórios
dados_w = np.random.randn(8,2)   # cria matriz de 8 linhas e 2 colunas com números aleatórios
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

b = tf.random.normal((4,2),0,1)   # cria matriz (tensor) de 4 linhas e 2 colunas com números aleatórios

x = tf.placeholder(tf.float32, shape=(4, 8))
w = tf.placeholder(tf.float32, shape=(8, 2))
operacao = tf.matmul(x, w) + b

maximo = tf.reduce_max(operacao) # encontra o maior valor da matriz operacao

with tf.Session() as sess:
        saida1 = sess.run(operacao, feed_dict={x: dados_x, w: dados_w})
        saida2 = sess.run(maximo, feed_dict={x: dados_x, w: dados_w}) 
print(saida2)





7.896382


In [14]:
print(saida1)

[[ 1.1744788   2.3344932 ]
 [-3.9109402   0.2309158 ]
 [ 2.0460591  -4.3584027 ]
 [ 0.25934982  3.9064217 ]]


In [16]:
import numpy as np

x1 = np.random.randn(4,8)  
w1 = np.random.randn(8,2)  

x2 = np.random.randn(4,8)  
w2 = np.random.randn(8,2)

x3 = np.random.randn(10,3)  
w3 = np.random.randn(3,1)

x4 = np.random.randn(4,8)  
w4 = np.random.randn(8,2)

x5 = np.random.randn(4,8)  
w5 = np.random.randn(8,2)

lista_x = [x1, x2, x3, x4, x5]
lista_w = [w1, w2, w3, w4, w5]
lista_saida = []

b = tf.random_normal((4,2),0,1)   # cria matriz (tensor) de 4 linhas e 2 colunas com números aleatórios

x = tf.placeholder(tf.float32, shape=(None, None))
w = tf.placeholder(tf.float32, shape=(None, None))
operacao = tf.matmul(x, w)

maximo = tf.reduce_max(operacao) # encontra o maior valor da matriz operacao

with tf.Session() as sess:
    for i in range(5):
        saida = sess.run(maximo, feed_dict={x: lista_x[i], w: lista_w[i]})
        lista_saida.append(saida)
print(lista_saida)

[8.6741905, 3.767013, 5.086779, 4.8658466, 1.0302074]
